version: '3.8'
services:
  web:
    image: obyte-aastats-frontend-image
    container_name: obyte-aastats-frontend-container
    build:
      context: .
    restart: always
    ports:
      - 80:80
      - 443:443
