const mdSmHomeLt = [
  {
    i: 'widget-1',
    x: 0,
    y: 0,
    w: 1,
    h: 1,
    isResizable: false,
    moved: false,
    static: false,
  },
  {
    i: 'widget-2',
    x: 1,
    y: 0,
    w: 1,
    h: 1,
    isResizable: false,
    moved: false,
    static: false,
  },
  {
    i: 'widget-3',
    x: 2,
    y: 0,
    w: 1,
    h: 1,
    isResizable: false,
    moved: false,
    static: false,
  },
  {
    i: 'widget-chart',
    x: 0,
    y: 1,
    w: 3,
    h: 2,
    minW: 2,
    minH: 2,
    maxW: 3,
    moved: false,
    static: false,
  },
];

const mdSmAgentLt = [
  {
    i: 'widget-1',
    x: 0,
    y: 0,
    w: 1,
    h: 1,
    isResizable: false,
    moved: false,
    static: false,
  },
  {
    i: 'widget-2',
    x: 0,
    y: 1,
    w: 1,
    h: 1,
    isResizable: false,
    moved: false,
    static: false,
  },
  {
    i: 'widget-chart',
    x: 1,
    y: 0,
    w: 2,
    h: 2,
    minW: 2,
    minH: 2,
    maxW: 3,
    moved: false,
    static: false,
  },
];

export const initialState: UIState = {
  darkMode: true,
  homeLayouts: {
    md: mdSmHomeLt,
    sm: mdSmHomeLt,
    xs: [
      {
        i: 'widget-1',
        x: 0,
        y: 0,
        w: 1,
        h: 1,
        maxW: 2,
        maxH: 1,
        moved: false,
        static: true,
      },
      {
        i: 'widget-2',
        x: 1,
        y: 0,
        w: 1,
        h: 1,
        maxW: 2,
        maxH: 1,
        moved: false,
        static: true,
      },
      {
        i: 'widget-3',
        x: 0,
        y: 1,
        w: 2,
        h: 1,
        maxW: 2,
        maxH: 1,
        moved: false,
        static: true,
      },
      {
        i: 'widget-chart',
        x: 0,
        y: 2,
        w: 2,
        h: 2,
        minW: 2,
        maxW: 2,
        moved: false,
        static: true,
      },
    ],
    xxs: [
      {
        i: 'widget-1',
        x: 0,
        y: 0,
        w: 1,
        h: 1,
        moved: false,
        static: true,
      },
      {
        i: 'widget-2',
        x: 0,
        y: 1,
        w: 1,
        h: 1,
        moved: false,
        static: true,
      },
      {
        i: 'widget-3',
        x: 0,
        y: 2,
        w: 1,
        h: 1,
        moved: false,
        static: true,
      },
      {
        i: 'widget-chart',
        x: 0,
        y: 3,
        w: 1,
        h: 2,
        maxW: 1,
        moved: false,
        static: true,
      },
    ],
  },
  agentLayouts: {
    md: mdSmAgentLt,
    sm: mdSmAgentLt,
    xs: [
      {
        i: 'widget-1',
        x: 0,
        y: 0,
        w: 1,
        h: 1,
        moved: false,
        static: true,
      },
      {
        i: 'widget-2',
        x: 1,
        y: 0,
        w: 1,
        h: 1,
        moved: false,
        static: true,
      },
      {
        i: 'widget-chart',
        x: 0,
        y: 1,
        w: 2,
        h: 2,
        minW: 2,
        maxW: 2,
        moved: false,
        static: true,
      },
    ],
    xxs: [
      {
        i: 'widget-1',
        x: 0,
        y: 0,
        w: 1,
        h: 1,
        moved: false,
        static: true,
      },
      {
        i: 'widget-2',
        x: 0,
        y: 1,
        w: 1,
        h: 1,
        moved: false,
        static: true,
      },
      {
        i: 'widget-chart',
        x: 0,
        y: 2,
        w: 1,
        h: 2,
        maxW: 1,
        moved: false,
        static: true,
      },
    ],
  },
  homeLayoutsCache: {},
  agentLayoutsCache: {},
  totalGraphPeriodControls: { label: '30 Days', value: 30, labelMobile: '30d' },
  totalGraphActivitiesControls: [
    {
      label: 'USD in',
      labelMobile: '$ in',
      value: 'usd_amount_in',
      color: '#ffa16f',
      timeframe: 'daily',
      group: 'usd',
      type: 'currency',
    },
  ],
  agentsTablePeriodControls: {
    label: 'Today',
    value: 1,
    timeframe: 'hourly',
    labelMobile: '2day',
  },
  agentsTableDataLimit: 10,
  agentsTableSortType: 'usd_amount_in',
  agentsTableSortByTvl: false,
  asset: 'all',
  assets: [],
  agentGraphActivitiesControls: [
    {
      label: 'USD in',
      labelMobile: '$ in',
      value: 'usd_amount_in',
      color: '#ffa16f',
      timeframe: 'daily',
      group: 'usd',
      type: 'currency',
    },
  ],
  agentGraphPeriodControl: { label: '30 Days', value: 30, labelMobile: '30d' },
};
